//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bookyourdoctor
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital_view
    {
        public System.TimeSpan hospital_time { get; set; }
        public System.DateTime date { get; set; }
        public string patient_name { get; set; }
        public string Hosspital_day { get; set; }
        public string doctor_id { get; set; }
    }
}
